version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }

  - package-ecosystem: docker
    directory: /
    schedule: { interval: monthly }

  - package-ecosystem: bun
    directory: /backend/src
    schedule: { interval: monthly }

  - package-ecosystem: bun
    directory: /frontend/src
    schedule: { interval: monthly }